### ISSUE TITLE
1.3.0 crashes (won't open)

### ISSUE THREAD

**Issue by gitterspec** [yaxarat/lingvaandroid#51] opened 2023-04-24 14:27 UTC
1.2.6 is working fine for me. Both installed from F-Droid

**Comment by yaxarat** [comment] 2023-04-24 18:56
Most likely a duplicate of this resolved issue: https://github.com/yaxarat/lingvaandroid/issues/48
The crash has been fixed and should be rolling out in 1.3.1 whenever Fdroid publishes the new version. 1.3.1 is already out on the Play Store btw.

**Closed as completed by yaxarat** 2023-04-24 18:56 UTC
